### ISSUE TITLE
Only leader scrape jobs are sent to Prometheus

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/alertmanager-k8s-operator#151]
### Enhancement Proposal

As @simskij said in [this comment](https://github.com/canonical/alertmanager-k8s-operator/pull/150#issuecomment-1513199310) Alertmanager is not providing a scrape job for all units, but only for the leader.

This is because Alertmanager requires `ingress-per-app`: 

```yaml
requires:
  ingress:
    interface: ingress
    limit: 1
    description: |
      Alertmanager typically needs a "per app" ingress, which is available in the traefik charm[1].

      [1] https://charmhub.io/traefik-k8s
```
We need `ingress-per-app` so alerts can be seen from outside the k8s cluster, but in the other hand we need `ingress-per-unit` so we can send unit scrapes jobs to Prometheus.
