### ISSUE TITLE
Grouping of alerts can not be disabled

### ISSUE THREAD

**Issue by marcusboden** [canonical/alertmanager-k8s-operator#205]
### Bug Description

Grouping of alerts can not be disabled. 

### To Reproduce

Put this into the config_file:
```yaml
route:
  group_by:
  - ...
```
This should disable grouping entirely, according to the [documentation](https://prometheus.io/docs/alerting/latest/configuration/#route-related-settings).

When rolled out, the unit goes into blocked state and amtool reports:
```
root@alertmanager-0:/# amtool check-config /etc/alertmanager/alertmanager.yml 
Checking '/etc/alertmanager/alertmanager.yml'  FAILED: cannot have wildcard group_by (`...`) and other other labels at the same time
```
The config itself has:
```yaml
route:
  group_by:
  - juju_model_uuid
  - juju_application
  - '...'
  - juju_model
```

### Environment

I tried this locally, as well as on customer clouds running latest/stable.

### Relevant log output

```shell
Checking '/etc/alertmanager/alertmanager.yml'  FAILED: cannot have wildcard group_by (`...`) and other other labels at the same time
```
