### ISSUE TITLE
version freeze everything

### ISSUE THREAD

**Issue by sed-i** [canonical/alertmanager-k8s-operator#52]
Before promoting the alertmanager-k8s charm to beta it might be a good idea to version lock a few things:
 
- [ ] pip packages
- [ ] image versions
- [ ] add to metadata: assumes: juju >= 2.9.23
- [ ] juju version for ci itests:

```yaml
    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        juju-channel: latest/candidate
```
